(require 'lambda-mode)
(setq lambda-regex "\\(lambda[ :]\\)")
(setq lambda-symbol (string (make-char 'greek-iso8859-7 107)))
; (add-hook 'python-mode-hook #'lambda-mode 1)
(add-hook 'emacs-lisp-mode-hook #'lambda-mode 1)
